// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive from "./Primitive.bs.js";

function validate(n) {
  if (n > 0) {
    return n;
  }
  
}

var include = Primitive.Make({
      validate: validate
    });

var make = include.make;

var value = include.value;

export {
  make ,
  value ,
}
/* include Not a pure module */
