// Generated by ReScript, PLEASE EDIT WITH CARE


function Make(C) {
  var value = function (v) {
    return v;
  };
  return {
          make: C.validate,
          value: value
        };
}

function validate(n) {
  if (n > 0) {
    return n;
  }
  
}

function value(v) {
  return v;
}

var PositiveInt = {
  make: validate,
  value: value
};

export {
  Make ,
  PositiveInt ,
}
/* No side effect */
