// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Result from "@rescript/core/src/Core__Result.res.js";
import * as S$RescriptSchema from "rescript-schema/src/S.res.js";

function Make(C) {
  var parse = function (v) {
    return S$RescriptSchema.parseWith(v, C.schema);
  };
  var parseExn = function (v) {
    return Core__Result.getExn(S$RescriptSchema.parseWith(v, C.schema));
  };
  var make = function (v) {
    var v$1 = C.toJson(v);
    return S$RescriptSchema.parseWith(v$1, C.schema);
  };
  var makeOpt = function (v) {
    var v$1 = make(v);
    if (v$1.TAG === "Ok") {
      return Caml_option.some(v$1._0);
    }
    
  };
  var makeExn = function (v) {
    return Core__Result.getExn(make(v));
  };
  var toJson = function (v) {
    return S$RescriptSchema.serializeOrRaiseWith(v, C.schema);
  };
  var eq = function (a, b) {
    return C.eq(a, b);
  };
  var neq = function (a, b) {
    return !C.eq(a, b);
  };
  return {
          make: make,
          makeOpt: makeOpt,
          makeExn: makeExn,
          toJson: toJson,
          parse: parse,
          parseExn: parseExn,
          eq: eq,
          neq: neq
        };
}

var S;

export {
  S ,
  Make ,
}
/* S-RescriptSchema Not a pure module */
