// Generated by ReScript, PLEASE EDIT WITH CARE


function Make(C) {
  var value = function (v) {
    return v;
  };
  return {
          make: C.validate,
          value: value
        };
}

export {
  Make ,
}
/* No side effect */
