// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ShortStringB from "./ShortStringB.res.mjs";

var a = ShortStringB.makeExn("hello");

var b = ShortStringB.makeExn("goodbye");

var areEqual = ShortStringB.eq(a, b);

var T;

export {
  T ,
  a ,
  b ,
  areEqual ,
}
/* a Not a pure module */
