// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive from "./Primitive.res.mjs";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";

function parse(j) {
  var decoded = Core__JSON.Decode.string(j);
  if (decoded === undefined) {
    return {
            TAG: "Error",
            _0: "expected a string"
          };
  }
  var s = decoded.trim();
  if (s.length > 10) {
    return {
            TAG: "Error",
            _0: "string is too long; must be 10 characters or fewer"
          };
  } else {
    return {
            TAG: "Ok",
            _0: s
          };
  }
}

function toJson(s) {
  return s;
}

function eq(a, b) {
  return a === b;
}

var Config = {
  parse: parse,
  toJson: toJson,
  eq: eq
};

var Contents = Primitive.Make(Config);

export {
  Config ,
  Contents ,
}
/* Contents Not a pure module */
