// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ShortStringA from "./ShortStringA.res.mjs";

var a = ShortStringA.Contents.makeExn("hello");

var b = ShortStringA.Contents.makeExn("goodbye");

var areEqual = ShortStringA.Contents.eq(a, b);

var T;

export {
  T ,
  a ,
  b ,
  areEqual ,
}
/* a Not a pure module */
