// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function add(a, b) {
  return a + b | 0;
}

function isNone(v) {
  return Core__Option.isNone(v);
}

var hello = "hello";

export {
  hello ,
  add ,
  isNone ,
}
/* No side effect */
